language: python
python:
  - "3.5"
  #- "nightly" # currently points to 3.6-dev
# command to install dependencies
install: "pip install -r requirements.txt && pip install -r requirements-dev.txt"
# command to run tests
script: nosetests
